# Site settings
title:  Yucan
header-img: "img/autumn2.jpg"
tagline: "风中等风来"  
description: "风中等风来"  
baseurl: ""
url: "http://yucan.win"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Yucan"
  email: zhyucan@gmail.com
  bio: "用舍由時，行藏在我。袖手何妨閑處看。"

# Data
gavatar: http://o7v1v0rr4.bkt.clouddn.com/IMG_0754.jpg
favicon: img/favicon.ico

douban_username: 56816118
twitter_username: zyucan  
github_username: zhyucan 
facebook_username: zhyucan  
weibo_username: 123152014  
zhihu_username: yucan  
email_username: zhyucan@gmail.com

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Guangzhou

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Yucan"
      header-img: "img/autumn2.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name : Yucan
  disqus :
    short_name : zhyucan

# Analytics and webmaster tools stuff goes here
google_analytics: UA-78450750-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation